// generated by cdktf get
Object.defineProperty(exports, 'resource', { get: function () { return require('./resource'); } });
Object.defineProperty(exports, 'dataNullDataSource', { get: function () { return require('./data-null-data-source'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

